### ISSUE TITLE
Error: Missing region in config

### ISSUE THREAD

**Issue by IgorXVI** [Fyreware/mysql-data-api#5]
I'm trying to use the package with sequelize but when i make a query i get this error:
```
Error [ConfigError]: Missing region in config
at Request.VALIDATE_REGION (C:\...\node_modules\aws-sdk\lib\event_listeners.js:92:45)
      at Request.callListeners (C::\...\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
      at callNextListener (C::\...\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
      at C:\...\node_modules\aws-sdk\lib\event_listeners.js:86:9
      at finish (C:\...\node_modules\aws-sdk\lib\config.js:379:7)
      at C:\...\node_modules\aws-sdk\lib\config.js:397:9
      at SharedIniFileCredentials.get (C::\...\node_modules\aws-sdk\lib\credentials.js:127:7)
      at getAsyncCredentials (C:\...\node_modules\aws-sdk\lib\config.js:391:24)
      at Config.getCredentials (C:\...\node_modules\aws-sdk\lib\config.js:411:9)
      at Request.VALIDATE_CREDENTIALS (C::\...\node_modules\aws-sdk\lib\event_listeners.js:81:26)
```

The same error happen when i try to instantiate the AWS-SDK DataService without specifying a region in the options object:

```javascript
const dataService = new AWS.RDSDataService({
     apiVersion: '2018-08-01'
}) 
dataService.executeSql({
     awsSecretStoreArn: process.env.DB_SECRET,
     dbClusterOrInstanceArn: process.env.DB_ARN,
      sqlStatements: "SELECT * FROM survey WHERE id = 1",
      database: process.env.DB_NAME
}, (err, data) => {
     if (err) {
          throw err
     }

     res.status(200).json(data)
})
```

If i specify the region, the error does not happen:

```javascript
const dataService = new AWS.RDSDataService({
     apiVersion: '2018-08-01',
     region: "us-east-1"
}) 
dataService.executeSql({
     awsSecretStoreArn: process.env.DB_SECRET,
     dbClusterOrInstanceArn: process.env.DB_ARN,
      sqlStatements: "SELECT * FROM survey WHERE id = 1",
      database: process.env.DB_NAME
}, (err, data) => {
     if (err) {
          throw err
     }

     res.status(200).json(data)
})
```

So i believe the problem is that the package does not inform the region internally, am i wrong?

**Comment by IgorXVI** [comment]
I did the following modifications and it solved the problem:
```javascript
let client;
class Connection extends EventEmitter {
  constructor({
    host, // Resource
    password, // SecretArn
    database, // Database
  }) {
    super();

    if (!client) {
      client = DataApi({
        resourceArn: host,
        secretArn: password,
        database,
        region: "us-east-1"
      });
    }
```
